"""
@date       171117 - Enhanced doc format

Query starred list from user github and export to markdown file.

IMPORTANT:
  * API limit: 60 times in one hour
  * You could check from 'https://api.github.com/rate_limit' by yourself.

Ref:
  * https://developer.github.com/v3/activity/starring/
  * https://developer.github.com/v3/#pagination
  * https://developer.github.com/v3/rate_limit/
"""
from datetime import datetime, date
import asyncio
import aiohttp


TARGET_OWNER = 'grtfou'  # ex. gvanrossum
OUTPUT_FILENAME = 'README.md'
API_URL = 'https://api.github.com'
REPO_LINK = 'https://github.com/grtfou/my-stars.git'


def _repos_checker(lng, proj, last_code_push):
    """
    Design a checker by user defined.
    """

    # For user to check old repository
    if int(last_code_push) > 540:  # 1.5 year
        print("({}, {} days) {}".format(
            lng, last_code_push, proj['full_name']))


async def fetch(client, page=1):
    """Get starred list.
    Other URL arguments:
      * page: ex. 3
      * per_page: ex. 100
    """
    url = '{}/users/{}/starred?page={}&per_page=100'.format(
        API_URL, TARGET_OWNER, page)
    header = {
        'content-type': 'application/vnd.github.v3+json'
    }
    async with client.get(url, headers=header) as resp:
        assert resp.status == 200
        # print(resp.headers.get('link').split(',')[-1])
        return await resp.json()


async def main(loop):
    data = {}
    async with aiohttp.ClientSession(loop=loop) as client:
        page = 1
        count = 0
        while True:
            try:
                json_repo = await fetch(client, page)
            except AssertionError:
                print('Fetch page fail.')
                break

            if not json_repo:
                break
            else:
                page += 1

            for proj in json_repo:
                count += 1
                lng = proj.get('language', '')
                if lng is None:
                    lng = 'DOCUMENT'
                else:
                    lng = lng.upper()

                if lng in data:
                    data[lng] += [proj]
                else:
                    data[lng] = [proj]

    print("Total starred repos: {}".format(count))
    with open(OUTPUT_FILENAME, 'w') as ffi:
        # project description
        ffi.write("This README.md is generated by code. {}\n\n".format(
                  date.today()))

        # setup
        ffi.write("#### How to use\n\n")
        ffi.write("```bash\n $ git clone {}\n"
                  " $ cd my-stars\n"
                  " $ pip install -r requirements.txt\n"
                  " $ python get_starred_list.py\n"
                  "```\n\n".format(REPO_LINK))

        # bookmark
        for lng in sorted(data):
            lng_bookmark = lng.lower()
            lng_name = lng
            lng_count = len(data[lng])

            if lng_bookmark == 'c++':
                lng_bookmark = 'c-2'

            lng_bookmark = lng_bookmark.replace(" ", "-")

            ffi.write("* [{}](#{}) ({})\n".format(
                lng_name, lng_bookmark, lng_count))

        ffi.write("\n")
        # repo stars
        for lng, projs in sorted(data.items(), key=lambda data: data[0]):
            ffi.write("# {} \n\n".format(lng))
            ffi.write("---\n\n")
            for proj in projs:
                pushed_at = datetime.strptime(
                    proj['pushed_at'], "%Y-%m-%dT%H:%M:%SZ")

                last_code_push = str((datetime.utcnow() - pushed_at).days)

                ffi.write("## {} \n\n".format(proj.get('name')))
                ffi.write("```\n{} \n```\n\n".format(
                    proj.get('description')))
                ffi.write("  * [Github]({})\n".format(proj['html_url']))
                ffi.write("  * Stars: {}\n".format(proj['stargazers_count']))
                ffi.write("  * Open issues: {}\n".format(
                    proj['open_issues_count']))
                ffi.write("  * Last pushed: {} ({} days)\n\n".format(
                    pushed_at.strftime("%Y-%m-%d"), last_code_push))

                # checker
                _repos_checker(lng, proj, last_code_push)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
